[general]
import = ["~/.config/alacritty/rose-pine.toml"]
[font]
normal = {family="ComicShannsMono Nerd Font Mono",style = "Regular"}
bold= {family="ComicShannsMono Nerd Font Mono",style = "Bold"}
size = 13


